// Declares a variable.
let userInput = 'BOMB';

// Reassigns the 'userInput' variable as lowercase
let userChoice = userInput.toLowerCase();

// Defines 'getUserChoice' function using a function expression, with userInput as a parameter. This checks that userInput value is valid and captures in Variable 'userChoice': 

const getUserChoice = function (userChoice) {
 if (userChoice === 'rock'){
   userChoice = userChoice;
 } else if (userInput === 'scissors') {
   userChoice = userChoice;
 } else if (userInput === 'paper') {
   userChoice = userChoice;
 } else if (userInput === 'bomb') {
   userChoice = userChoice;
 } else {
   userChoice = 'input invalid'
 }
 }

getUserChoice(userChoice);

// Prints the value inputted by Player (if valid)
console.log (`Player1: ${userChoice}`)
// Declares function using the 'function' keyword: 
function getComputerChoice () {return Math.floor(Math.random()*3)}
let computerNumber = getComputerChoice()
// Captures 0,1 or 2 as a variable

// Defines Arrow function:
const convertComputerChoice = computerNumber => {
if (computerNumber === 0){
  computerChoice = 'rock';
} else if (computerNumber === 1) {
  computerChoice ='paper'; 
} else {
  computerChoice = 'scissors';
}
}

// calls convertedComputerChoice function 
convertComputerChoice (computerNumber);
// Prints the value generated by Computer
console.log(`Computer: ${computerChoice}.`)

function determineWinner (userChoice, computerChoice) {
  if (userChoice === computerChoice) {
    return 0;
  } else if (userChoice === 'bomb') {
    return "Player1 cheats but wins!"
  } else if (userChoice === 'rock' && computerChoice === 'scissors') {
    return "Player1 wins!";
  } else if (userChoice === 'scissors' && computerChoice === 'paper') {
    return "Player1 wins!";
  } else if (userChoice === 'paper' && computerChoice === 'rock') {
    return "Player1 wins!";
  } else { return "Computer wins!"}
}

console.log (determineWinner (userChoice, computerChoice) || "It's a tie!")

//Lessons: 
// Take care that strings are defined with " ... " . Numbers do not need " ...".
// Else...if statements should be If...Else if...Else
// Count your brackets (as well as your blessings)