/* << HTTP REQUESTS >>
Understanding the basics of how your web browser communicates with the internet

// 1. BACKGROUND >> 

The CA webpage is generated by a web of HTML, CSS & JS sent to you by CA via the Internet. 
The Internet is made up of a bunch of resources hosted on diff servers. 
'resource' being any entity on the web (HTML files, stylesheets, images, videos, scripts)
To access internet content, browsers ask servers for resources it wants, then displays them to you. 
This protocol of requests/responses enables you to view pages in your browser. 

This article focuses on one fundamental part of how internet functions: HTTP

-------------- 

// 2. What is HTTP? >> Hypertext Transfer Protocol

HTTP is used to structure requests & responses over the internet. 
HTTP requires data to be transferred from one point to another over the network. 

The transfer of data happens using TCP (Transmission Control Protocol)
In viewing a webpage, TCP manages the channels between your browser and the server (origin)
TCP manages many types of connections where one computer/device wants to send something to another

HTTP is the command language that devices on both sides of the connection must follow to communicate

-------------- 

// 3. HTTP & TCP: How It Works

When you type an address into the browser: www.codecademy.com 
You are commanding it to open a TCP channel to the server that responds to the URL*
In this situ, your computer making a request, is called THE CLIENT
The URL you request is the address that belongs to the server

*URL = Uniform Resource Locator (like a home address / phone no. describes how to reach you)

Once TCP connection established, the client sends a HTTP 'GET' request 
to the server to retrieve the webpage it should display.
After the server has sent a response, it closes the TCP connection. 

If you open the website in your browser again, a new connection is opened following the same process.
GET requests are one kind of HTTP method a client can call. 
Others common ones include POST, PUT, DELETE. 
Article: https://www.codecademy.com/articles/what-is-rest
https://www.codecademy.com/articles/what-is-crud
GET are the most common type of request & used to help the client access resources on the web. 

Suppose you want to access a CA course. After you type in URL...
Your browser will extract the 'http' part and recognise its the name of the network protocol to use 
Then, it takes the domain name from the URL 'codeacademy.com' and asks the internet
Domain Name Server to return an Internet Protocol (IP) address. 

Now the client knows the IP address.
It opens a connection to the server at that address, using the specified http protocol.
It initiates a GET request to the server containing the host's IP address and optionally, data payload. 
The GET request contains the following text: 

GET / HTTP/1.1
Host: www.codecademy.com

This identifies type of request, the path on www.codeacademy.com (in this case / ), and protocol:
HTTP/1.1 is a revision of the first HTTP, which is now called HTTP/1.0.
In HTTP/1.0, every resource request requires a seperate connection to the server
HTTP/1.1 uses one connection more than once, 
so that add. content (eg images) is retreived even after the page has been.
As result, HTTP/1.1 have less of a delay than HTTP/1.0.
The second line of the request contains the address of the server which is 'www.codeacademy.com'

If the server locates the path requested, the server might respond with the header:

HTTP/1.1 200 OK
Content-Type: text/html

The header is followed by the content requested, eg info needed to render www.codeacademy.com
The first line of the header HTTP/1.1 200 OK is confirmation that the server understands the protocol
that the client wants to communicate with (HTTP/1.1) 
and an HTTP status '200' signifies that the resource was found on the server
The first line 'Content-Type: text/html shows the type of content it will sent to the client

If the server is not able to locate the path requested by the client, it responds with header:
HTTP/1.1 404 NOT FOUND

The server identifies that it understands the HTTP protocol, but the 404 NOT FOUND status code
signifies that the specific piece of content requested was not found.
This may happen if content is moved, page removed or you typed in the URL path incorrectly
Read more about 404 status error error: https://www.codecademy.com/articles/http-errors-404 */





